export const path = {
  dashboard: '/',
  login: '/login',
  register: '/register',
  logout: '/logout',
  category: '/category',
  addCategory: '/add-category',
  updateCategory: '/update-category/:id',
  subcategory: '/subcategory',
  addSubcategory: '/add-subcategory',
  updateSubcategory: '/update-subcategory/:id',
  product: '/product',
  addProduct: '/add-product',
  updateProduct: '/update-product/:id',
  version: '/version',
  accessory: '/accessory',
  addVersion: '/add-version',
  updateVersion: '/update-version/:id',
  staff: '/staff',
  addStaff: '/add-staff',
  updateStaff: '/update-staff/:id',
  customer: '/customer',
  order: '/order',
  profile: '/profile',
  noPermission: '/no-permission'
}
